### ISSUE TITLE
[Enhancement] Make percentages round with a little more precision

### ISSUE THREAD

**Issue by blhylton** [Rexios80/SR-Tracker-for-Overwatch#2]
Don't have a developer environment on this machine or I would submit this as a pull request.

It would be nice if percentages (for example, win/loss/draw percentages on maps) rounded to something a bit more precise than an integer. This can be done by changing:

`Math.round(((float) wins / (wins + losses + draws)) * 100);`

to

`Math.round(((float) wins / (wins + losses + draws)) * 10000) / 100;`

and storing the values as `float`s instead of `int`s.

If I find time to do this, I'll send a pull request, but it shouldn't take but a second to change regardless of who gets to it first.

**Comment by Rexios80** [comment]
I'm fine with this as long as it doesn't break my layout and make the text wrap. Also I would prefer 100's stay without following zeroes.

**Comment by blhylton** [comment]
Actually, now that I'm thinking about it, why store these in a property and why round for storage? Just keep up with the wins, losses, and draws and do a derived property.

`getWinPercentage(){
  return ((float) wins / (wins + loses + draws)) * 100;
}

getWinPercentageAsString(){
  float result = this.getWinPercentage();
  
  if(result == 100.0f){
    return String.format('%.0f', result);
  }

  return String.format('%.2f', result);
}
`

Just not sure if there's a particular reason that you're handling it the way you are.

**Comment by Rexios80** [comment]
I just like setting variables before I get them. That's all.

**Comment by blhylton** [comment]
That's fair enough. It's a design decision because you're either taking up RAM or CPU. In this case, the performance hit is small enough not to really matter either way.

The way I personally view it is, if it is a number that is going to change dependent on already existing values in the data structure, I'll treat it as a derived property unless I have a specific reason not to (e.g. a particularly cumbersome algorithm that takes a while to generate it). But, this also stems from the way I design models. If I have a property for it then it's going in a long term data store and I only want to store as much as I need to.
