### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by blhylton** [Rexios80/SR-Tracker-for-Overwatch#3]
You should probably include a Readme.md in the root of the project describing what the project is and maybe including a license for utilizing the source code.

**Comment by Rexios80** [comment]
I wanted to add those, I just wasn't really sure what to put in the readme or which license to use.

**Comment by blhylton** [comment]
I can't really help you with the license as it's up to you how you want to allow your software to be distributed.

As for the Readme, it doesn't have to be anything specific. Just a quick blurb about what that app is and what it does, with a link to the play store page.
