### ISSUE TITLE
Request - Allow "Lucio" for text prediction on Lúcio.

### ISSUE THREAD

**Issue by rxbrad** [Rexios80/SR-Tracker-for-Overwatch#4]
Just a little quality-of-life change that'd be nice... Great app!

**Comment by Rexios80** [comment]
I'm not saying this isn't something I can add, but is there a reason you can't just type "L" or "l" and click on the completion for Lúcio?

**Comment by rxbrad** [comment]
An "L" alone totally works. I just know that the first time I tried to
enter it, I quickly typed LU and wondered where he was.

No biggie. I'll leave it up to you.

**Comment by Rexios80** [comment]
Added in v2.6
