### ISSUE TITLE
Request: My Team Vs Their Team SR Tracking & Time/Date Tracking

### ISSUE THREAD

**Issue by WasabiCannon** [Rexios80/SR-Tracker-for-Overwatch#5]
Since I heard MasterDex is dropping his tracker Im jumping ship to your app 

Im a HUGE stat slut and so far the 2 features of MasterDex's sheet that Im missing the most is the My Team vs Their Team SR and the Time/Date Tracking parts.

Do you have any plans to maybe add this?

**Comment by Rexios80** [comment]
I could, but I honestly don't know where I'd put it on the screen after you enter it as I'm already using up all available screen real estate. I'll try and fit it somewhere, but I can't promise it'll make it in.

**Comment by Rexios80** [comment]
Oh and time/date tracking is already in. Just touch an entry to see when you tracked it.

**Comment by Rexios80** [comment]
Sorry I'd just woken up when I made those first two comments.

I could add Team SR tracking, but I don't know where I'd put it on the screen. I'll try and fit it somewhere, but I can't promise it'll make it in.

Also, time and date tracking is already in. It's tracked automatically. Just touch an entry to see the time and date you entered it.

**Comment by WasabiCannon** [comment]
So with the time tracking it is simply just logging when a match happened.
For MasterDex's Time & Date tracking I talking about his section where it recommends a time and day to play and show your best month.

**Comment by Rexios80** [comment]
Oh okay. Well I already track the time so I guess I could work on using it to figure all that out. It'll go on my to-do list.

**Comment by Rexios80** [comment]
I've done some research and I should be able to make the items in the stats list expand on touch to show more information. This will give me plenty of room to add any data people want.

**Comment by WasabiCannon** [comment]
Oh dam nice. Guess that means maybe even splitting up the Maps & Heros for the winrates? 

That way in the future we could even get a way to filter the data.

**Comment by Rexios80** [comment]
You probably already know, but I added Team and Enemy SR tracking. 

Time analysis is on my to-do list and will get done when I get around to deciphering the gigantic Excel equations MasterDex used for his calculations.

**Comment by Rexios80** [comment]
Time analysis is in v2.0. Please let me know if you have any feedback.

**Comment by Rexios80** [comment]
Just wanted to let you know I added search in v2.7 because you mentioned it here. Thanks for the idea!
