### ISSUE TITLE
Request - Add a horizontal line to the SR graph representing the average SR

### ISSUE THREAD

**Issue by samperlmutter** [Rexios80/SR-Tracker-for-Overwatch#8]
This is something that I think would be interesting to see because it would show level you're kind of fluctuating around. Also as an aesthetic suggestion: I'm not sure if you're able to this, but it would be nice if the line of the SR graph was smooth and curved instead of straight lines. Personally, I just don't really like how jagged the graph end up looking. 

If you're not sure what I mean, here's a picture of the graph from an SR tracker spreadsheet I used to use:

![image](https://user-images.githubusercontent.com/6434256/27015684-d74b11ca-4ee2-11e7-9351-0a4874a5cb03.png)

**Comment by Rexios80** [comment]
The average line should be easy enough, I just have to figure out what color to make it. I don't know about reusing the blue because I've associated that color with losing. Color suggestions are welcome.

As for smoothing the line out: it really depends on if the library I'm using supports it. From what I've read so far it doesn't appear to. It will go on my to-do list, but I don't know if I'll be able to implement it any time soon.

**Comment by samperlmutter** [comment]
How about #a563fe? It's a light purple that I think is a good compromise between the dark grey-blue of the background, the orange win line, and the light blue loss line.

![screenshot_20170611-202706](https://user-images.githubusercontent.com/6434256/27016046-127a7ff0-4ee9-11e7-87fd-6c83bc1a80f0.png)

**Comment by Rexios80** [comment]
That looks great! I was thinking about using purple anyway, so I'll probably use that color. Thanks for the awesome feedback!

**Comment by samperlmutter** [comment]
No problem, dude.

**Comment by Rexios80** [comment]
Average SR line added in v2.2

**Comment by Rexios80** [comment]
I'm looking at the line on my phone, and it seems to be a much brighter purple than the one in the picture you sent. Are you sure that's the correct hex code?

**Comment by Rexios80** [comment]
This is #842BFD, which seems to be a little closer.

![screenshot_1497303851](https://user-images.githubusercontent.com/7896519/27056612-c2590704-4f96-11e7-9d5e-bd69507b5d58.png)

**Comment by samperlmutter** [comment]
I made my mock up in paint and my pc has a much worse screen than my phone so it would make sense for it look a little different. Is #842BFD what's on the live version or is that a build on your phone/emulator?  updated the app on my phone and the color looks different in the app than in your screenshot.

**Comment by Rexios80** [comment]
The color in the live version is the color you gave me. The screenshot I sent is a debug build I made to test the deeper purple I color picked from your screenshot. I couldn't really tell the color was off until I updated the app on my phone.

**Comment by samperlmutter** [comment]
Yeah, there's a very noticeable difference on my phone between the two builds and I do like the darker purple that you found better.

**Comment by Rexios80** [comment]
Cool. Since I don't want to push another update so soon for such a small issue, this will be in my next release.

**Comment by samperlmutter** [comment]
Great, glad this is finally resolved.
